spring:
  datasource:
    url: jdbc:h2:file:./data/imagedb
    username: admin
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
  h2: 
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-kmvjpaqa2nvf0dyq.us.auth0.com/
          audiences: https://image-library
         